stages:
  - build
  - deploy

build:
  image: maven:latest
  stage: build
  tags:
    - ugrad
  script: 
    - mvn clean install -X 
  artifacts:
    paths:
      - target

deploy:
  stage: deploy
  image: maven:latest
  tags:
    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - echo ${CI_COMMIT_REF_NAME}
    - echo ${CI_COMMIT_SHORT_SHA}
  script:
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"