stages:
  - build
  - deploy

build:
  image: maven:latest
  stage: build
  tags:
    - ugrad
  script: 
    - mvn clean install -X 
  artifacts:
    paths:
      - target

deploy:
  stage: deploy
  image: maven:latest
  tags:
    - ugrad
  script:
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" "${CI_COMMIT_SHORT_SHA}.zip" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"