image: maven:latest

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn clean test
