stages:
  - build_test
  - deploy_test

build_test:
  image: maven
  stage: build_test
  tags:
    - ugrad
  script: 
    - mvn clean install -X 
  artifacts:
    paths:
      - target

deploy_test:
  stage: deploy_test
  image: maven
  tags:
    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - zip -r DHL_$(date "+%Y.%m.%d-%H.%M.%S").zip target
    - scp -r -o StrictHostKeyChecking=no -i DHL_$(date "+%Y.%m.%d-%H.%M.%S").zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/DHL_$(date "+%Y.%m.%d-%H.%M.%S").zip"