image: maven:latest

build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/

test:
  stage: test
  tags:
    - ugrad
  script:
    - mvn verify

