image: maven:latest

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn clean test
    
deploy:
  stage: deploy
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip ${DEPLOY_DIR}
    - scp -r -o StrictHostKeyCheckin=no -i "${DEPLOY_SSH_KEY}" /target/*.jar "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"
  tags:
    - dalfcs_gitlab_docker_ci
